require('dotenv').config();

const POSTGRES_HOST = process.env.POSTGRES_HOST;
const POSTGRES_PORT = Number(process.env.POSTGRES_PORT);
const POSTGRES_USER = process.env.POSTGRES_USER;
const POSTGRES_PASSWORD = process.env.POSTGRES_PASSWORD;
const POSTGRES_DB = process.env.POSTGRES_DB;

const PORT = process.env.SERVER_PORT;

const PASSWORD_SALT = process.env.PASSWORD_SALT;
const ACCESS_TOKEN_SALT = process.env.ACCESS_TOKEN_SALT;
const REFRESH_TOKEN_SALT = process.env.REFRESH_TOKEN_SALT;
const ACCESS_TOKEN_EXPIRE = 60 * 60 * 24 * 1000;
const REFRESH_TOKEN_EXPIRE = 60 * 60 * 24 * 30 * 1000;

const REDIS_HASH_TIME_TO_LIVE = 7200;
const REDIS_HOST = process.env.REDIS_HOST;
const REDIS_PORT = process.env.REDIS_PORT;

module.exports = {
  POSTGRES_DB,
  POSTGRES_HOST,
  POSTGRES_PASSWORD,
  POSTGRES_PORT,
  POSTGRES_USER,
  PORT,
  PASSWORD_SALT,
  ACCESS_TOKEN_SALT,
  REFRESH_TOKEN_SALT,
  ACCESS_TOKEN_EXPIRE,
  REFRESH_TOKEN_EXPIRE,
  REDIS_HASH_TIME_TO_LIVE,
  REDIS_HOST,
  REDIS_PORT,
};
